services:
  - type: web
    name: crimson-petal
    runtime: python
    rootDir: yandere-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT4_TOKEN
        sync: false
